### PR TITLE
Updated migrations and seed file

### PR DESCRIPTION
**Pull request by muzza3000**
Hi Both,

I have updated the "seed.rb" file to create 15 boats in the Oslo area (GPS lat and long are randomly sampled from the correct area), assigned to 10 users.

I also realized that the standard "address:references" command makes it a requirement that a user has an address... this was tripping up the signup process, therefore I have updated the migrations to make this optional, but there was no easy way to do this that I could find to update from a future migration. 
You can read more about this here if you are interested: https://github.com/rails/rails/issues/37858

⚠ Therefore it would be better if you can run
`rails db:drop, db:create, db:migrate, db:seed` 
again. 

Finally I have updated the rails routes to the spec outlined in the excel sheet.

### CODE REVIEW

**Comment by stijoh** [comment]
Looks good

**Review by stijoh — APPROVED** [review]

**Comment by guilherme-andrade** [comment]
Great PR guys. Love to see this.

I have one question though, did you look at the google maps lecture to add latitude and longitude to your addresses?

**Comment by muzza3000** [comment]
Thanks Gui :-), yes i realize that we may want to geocode the lat long from the address input, but we may also want to pick the point on a map (as it is a boat and maybe it would be cool to pinpoint the exact dock in the marina - just an idea), so until we make that call we can have some seeded GPS points and then change after accordingly, if this is what you were implying?

**Comment by guilherme-andrade** [comment]
Yes, you got it. Just wanted to make sure you guys knew 👍

**Pull request merged**
